### ISSUE TITLE
2 cars missing on the website, but...

### ISSUE THREAD

**Issue by EstebanMz** [Re-Volt-America/Website#34]
Donnie TC (Advanced) and Sideswipe (Super Pro) are both in the game pack and in the web assets but are not visible in the webpage. But if they're added that would sum 36 cars on each class when every other has 35 vehicles, which seems to be the intended value of cars per class.

**Comment by BGMP** [comment]
Thanks a lot for reporting. The issue has been resolved and will come live on the site as soon as it deploys.

Ref: https://github.com/Re-Volt-America/Website/commit/a4bd1335fcc2d81ae3a1522a1724d0a07514b7a7
Ref: https://github.com/Re-Volt-America/RVA-Data/commit/30a7d7a97753ebf530f2a8716bc22ce763aa61fb
