### ISSUE TITLE
Add a rule to restrict username characters

### ISSUE THREAD

**Issue by BGMP** [Re-Volt-America/Website#44]
To play on RVA and be indexed in our official results, players must choose a nickname which matches the following regular expression:

- `/\A([a-zA-Z0-9_]{1,16}|[0-9a-f]{24})\z/`: https://regexr.com/77i9c  (Can be alphanumeric, 16 characters max and may include underscores)

Therefore we should have a rule over at https://rva.lat/rules explaining this restriction.

**Comment by EstebanMz** [comment]
Without having in mind translations to other languages, this issue has been solved already.

**Comment by BGMP** [comment]
Thanks @EstebanMz . You may close issues like this in the future too, I'm pretty sure you're allowed to.

Solved by: https://github.com/Re-Volt-America/Website/commit/49b98e0dfb7c34c1a61b90cf2670a186bcdf53ef
